branch-defaults:
  master:
    environment: chaltteok-pp-dev
    group_suffix: null
global:
  application_name: chaltteok-pp
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
